//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfuserEx_Additions.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConfuserEx_Additions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Anti De4Dot 的本地化字符串。
        /// </summary>
        internal static string AntiDe4DotPhase_Name {
            get {
                return ResourceManager.GetString("AntiDe4DotPhase_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prevents usage of De4Dot. 的本地化字符串。
        /// </summary>
        internal static string AntiDe4DotProtection_Description {
            get {
                return ResourceManager.GetString("AntiDe4DotProtection_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Anti De4Dot Protection 的本地化字符串。
        /// </summary>
        internal static string AntiDe4DotProtection_Name {
            get {
                return ResourceManager.GetString("AntiDe4DotProtection_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Anti-dnspy injection 的本地化字符串。
        /// </summary>
        internal static string AntiDnSpyPhase_Name {
            get {
                return ResourceManager.GetString("AntiDnSpyPhase_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This protection prevents dnspy. 的本地化字符串。
        /// </summary>
        internal static string AntiDnSpyProtection_Description {
            get {
                return ResourceManager.GetString("AntiDnSpyProtection_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Anti DnSpy Protection 的本地化字符串。
        /// </summary>
        internal static string AntiDnSpyProtection_Name {
            get {
                return ResourceManager.GetString("AntiDnSpyProtection_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Anti Dump Injection 的本地化字符串。
        /// </summary>
        internal static string AntiDumpPhase_Name {
            get {
                return ResourceManager.GetString("AntiDumpPhase_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This protection prevents memory dumping. 的本地化字符串。
        /// </summary>
        internal static string AntiDumpProtection_Description {
            get {
                return ResourceManager.GetString("AntiDumpProtection_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Anti Dump Protection 的本地化字符串。
        /// </summary>
        internal static string AntiDumpProtection_Name {
            get {
                return ResourceManager.GetString("AntiDumpProtection_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Anti VM Injection 的本地化字符串。
        /// </summary>
        internal static string AntiVMPhase_Name {
            get {
                return ResourceManager.GetString("AntiVMPhase_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This protection prevents the assembly from being run on a VM. 的本地化字符串。
        /// </summary>
        internal static string AntiVMProtection_Description {
            get {
                return ResourceManager.GetString("AntiVMProtection_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Anti Virtual Machine Protection 的本地化字符串。
        /// </summary>
        internal static string AntiVMProtection_Name {
            get {
                return ResourceManager.GetString("AntiVMProtection_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProtectedBy attribute removal 的本地化字符串。
        /// </summary>
        internal static string AntiWatermarkPhase_Name {
            get {
                return ResourceManager.GetString("AntiWatermarkPhase_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Removes the ProtectedBy watermark to prevent Protector detection. 的本地化字符串。
        /// </summary>
        internal static string AntiWatermarkProtection_Description {
            get {
                return ResourceManager.GetString("AntiWatermarkProtection_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Anti Watermark 的本地化字符串。
        /// </summary>
        internal static string AntiWatermarkProtection_Name {
            get {
                return ResourceManager.GetString("AntiWatermarkProtection_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Callvirt Protection 的本地化字符串。
        /// </summary>
        internal static string CallvirtPhase_Name {
            get {
                return ResourceManager.GetString("CallvirtPhase_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This protection encodes and compresses constants in the code. 的本地化字符串。
        /// </summary>
        internal static string ConstantProtection_Description {
            get {
                return ResourceManager.GetString("ConstantProtection_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Constants Protection 的本地化字符串。
        /// </summary>
        internal static string ConstantProtection_Name {
            get {
                return ResourceManager.GetString("ConstantProtection_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Control flow mangling 的本地化字符串。
        /// </summary>
        internal static string ControlFlowPhase_Name {
            get {
                return ResourceManager.GetString("ControlFlowPhase_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to calcuate maxstack. 的本地化字符串。
        /// </summary>
        internal static string ControlFlowPhase_ProcessMethod_Failed {
            get {
                return ResourceManager.GetString("ControlFlowPhase_ProcessMethod_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This protection mangles the code in the methods so that decompilers cannot decompile the methods. 的本地化字符串。
        /// </summary>
        internal static string ControlFlowProtection_Description {
            get {
                return ResourceManager.GetString("ControlFlowProtection_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Control Flow Protection 的本地化字符串。
        /// </summary>
        internal static string ControlFlowProtection_Name {
            get {
                return ResourceManager.GetString("ControlFlowProtection_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctor Call Protection 的本地化字符串。
        /// </summary>
        internal static string CtorCallProtection_Name {
            get {
                return ResourceManager.GetString("CtorCallProtection_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Constants encoding 的本地化字符串。
        /// </summary>
        internal static string EncodePhase_Name {
            get {
                return ResourceManager.GetString("EncodePhase_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This protection flood the module.cctor. 的本地化字符串。
        /// </summary>
        internal static string EraseHeadersProtection_Description {
            get {
                return ResourceManager.GetString("EraseHeadersProtection_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 erase headers Protection 的本地化字符串。
        /// </summary>
        internal static string EraseHeadersProtection_Name {
            get {
                return ResourceManager.GetString("EraseHeadersProtection_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Erasing Headers 的本地化字符串。
        /// </summary>
        internal static string ErasePhase_Name {
            get {
                return ResourceManager.GetString("ErasePhase_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Added attribute  的本地化字符串。
        /// </summary>
        internal static string FakeObfuscatorAttributesPhase_InjectType_Debug {
            get {
                return ResourceManager.GetString("FakeObfuscatorAttributesPhase_InjectType_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fake obfuscator attribute addition 的本地化字符串。
        /// </summary>
        internal static string FakeObfuscatorAttributesPhase_Name {
            get {
                return ResourceManager.GetString("FakeObfuscatorAttributesPhase_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confuses obfuscators like de4dot by adding types typical to other obfuscators. 的本地化字符串。
        /// </summary>
        internal static string FakeObfuscatorProtection_Description {
            get {
                return ResourceManager.GetString("FakeObfuscatorProtection_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fake Obfuscator Protection 的本地化字符串。
        /// </summary>
        internal static string FakeObfuscatorProtection_Name {
            get {
                return ResourceManager.GetString("FakeObfuscatorProtection_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Added type  的本地化字符串。
        /// </summary>
        internal static string FakeObfuscatorTypesPhase_InjectType_Debug {
            get {
                return ResourceManager.GetString("FakeObfuscatorTypesPhase_InjectType_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fake obfuscator type addition 的本地化字符串。
        /// </summary>
        internal static string FakeObfuscatorTypesPhase_Name {
            get {
                return ResourceManager.GetString("FakeObfuscatorTypesPhase_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hash Phase 的本地化字符串。
        /// </summary>
        internal static string HashPhase_Name {
            get {
                return ResourceManager.GetString("HashPhase_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide Calls Injection 的本地化字符串。
        /// </summary>
        internal static string HideCallsPhase_Name {
            get {
                return ResourceManager.GetString("HideCallsPhase_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This protection crash .cctor. 的本地化字符串。
        /// </summary>
        internal static string HideCallsProtection_Description {
            get {
                return ResourceManager.GetString("HideCallsProtection_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide Calls Protection 的本地化字符串。
        /// </summary>
        internal static string HideCallsProtection_Name {
            get {
                return ResourceManager.GetString("HideCallsProtection_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Constant encryption helpers injection 的本地化字符串。
        /// </summary>
        internal static string InjectPhase_Name {
            get {
                return ResourceManager.GetString("InjectPhase_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This protection hashs the module to preventing file modifications. 的本地化字符串。
        /// </summary>
        internal static string IntegrityChecker_Description {
            get {
                return ResourceManager.GetString("IntegrityChecker_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Integrity Protection 的本地化字符串。
        /// </summary>
        internal static string IntegrityChecker_Name {
            get {
                return ResourceManager.GetString("IntegrityChecker_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  MD5 Hash Check Injection 的本地化字符串。
        /// </summary>
        internal static string IntegrityPhase_Name {
            get {
                return ResourceManager.GetString("IntegrityPhase_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Encrypting method section... 的本地化字符串。
        /// </summary>
        internal static string JITMode_OnWriterEvent_Encrypting_method_section {
            get {
                return ResourceManager.GetString("JITMode_OnWriterEvent_Encrypting_method_section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extracting method bodies... 的本地化字符串。
        /// </summary>
        internal static string JITMode_OnWriterEvent_Extracting_method_bodies {
            get {
                return ResourceManager.GetString("JITMode_OnWriterEvent_Extracting_method_bodies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ldfld Protection 的本地化字符串。
        /// </summary>
        internal static string LdfldPhase_Name {
            get {
                return ResourceManager.GetString("LdfldPhase_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local-to-field executing 的本地化字符串。
        /// </summary>
        internal static string localtofieldphase_Name {
            get {
                return ResourceManager.GetString("localtofieldphase_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This protection marks the module with a attribute that discourage ILDasm from disassembling it. 的本地化字符串。
        /// </summary>
        internal static string LocaltoFieldProtection_Description {
            get {
                return ResourceManager.GetString("LocaltoFieldProtection_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 local to field Protection 的本地化字符串。
        /// </summary>
        internal static string LocaltoFieldProtection_Name {
            get {
                return ResourceManager.GetString("LocaltoFieldProtection_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiply Protection 的本地化字符串。
        /// </summary>
        internal static string MultiplyPhase_Name {
            get {
                return ResourceManager.GetString("MultiplyPhase_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mutating Constants 的本地化字符串。
        /// </summary>
        internal static string MutateConstantsPhase_Name {
            get {
                return ResourceManager.GetString("MutateConstantsPhase_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This protection mutate Contants with sizeofs. 的本地化字符串。
        /// </summary>
        internal static string MutateConstantsProtection_Description {
            get {
                return ResourceManager.GetString("MutateConstantsProtection_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mutate Constants 的本地化字符串。
        /// </summary>
        internal static string MutateConstantsProtection_Name {
            get {
                return ResourceManager.GetString("MutateConstantsProtection_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Protects OpCodes such as Ldlfd. 的本地化字符串。
        /// </summary>
        internal static string OpCodeProtection_Description {
            get {
                return ResourceManager.GetString("OpCodeProtection_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpCode Protection 的本地化字符串。
        /// </summary>
        internal static string OpCodeProtection_Name {
            get {
                return ResourceManager.GetString("OpCodeProtection_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This optimization remove unnecessary metadata. 的本地化字符串。
        /// </summary>
        internal static string ReduceMetadataOptimization_Description {
            get {
                return ResourceManager.GetString("ReduceMetadataOptimization_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reduce Metadata Confusion 的本地化字符串。
        /// </summary>
        internal static string ReduceMetadataOptimization_Name {
            get {
                return ResourceManager.GetString("ReduceMetadataOptimization_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reduce Metadata Confusion 的本地化字符串。
        /// </summary>
        internal static string ReduceMetadataOptimizationPhase_Name {
            get {
                return ResourceManager.GetString("ReduceMetadataOptimizationPhase_Name", resourceCulture);
            }
        }
    }
}
