//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Confuser.Protections.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Confuser.Protections.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Type scanner 的本地化字符串。
        /// </summary>
        internal static string AnalyzePhaseName {
            get {
                return ResourceManager.GetString("AnalyzePhaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Anti-debug injection 的本地化字符串。
        /// </summary>
        internal static string AntiDebugProtectionAntiDebugPhaseName {
            get {
                return ResourceManager.GetString("AntiDebugProtectionAntiDebugPhaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This protection prevents the assembly from being debugged or profiled. 的本地化字符串。
        /// </summary>
        internal static string AntiDebugProtectionDescription {
            get {
                return ResourceManager.GetString("AntiDebugProtectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Anti Debug Protection 的本地化字符串。
        /// </summary>
        internal static string AntiDebugProtectionName {
            get {
                return ResourceManager.GetString("AntiDebugProtectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Anti-dump injection 的本地化字符串。
        /// </summary>
        internal static string AntiDumpPhase_Name {
            get {
                return ResourceManager.GetString("AntiDumpPhase_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This protection prevents the assembly from being dumped from memory. 的本地化字符串。
        /// </summary>
        internal static string AntiDumpProtectionDescription {
            get {
                return ResourceManager.GetString("AntiDumpProtectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hardening Phase 的本地化字符串。
        /// </summary>
        internal static string AntiDumpProtectionName {
            get {
                return ResourceManager.GetString("AntiDumpProtectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Anti-ILDasm marking 的本地化字符串。
        /// </summary>
        internal static string AntiILDasmPhaseName {
            get {
                return ResourceManager.GetString("AntiILDasmPhaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This protection marks the module with a attribute that discourage ILDasm from disassembling it. 的本地化字符串。
        /// </summary>
        internal static string AntiILDasmProtectionDescription {
            get {
                return ResourceManager.GetString("AntiILDasmProtectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Anti IL Dasm Protection 的本地化字符串。
        /// </summary>
        internal static string AntiILDasmProtectionName {
            get {
                return ResourceManager.GetString("AntiILDasmProtectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This protection ensures the integrity of application. 的本地化字符串。
        /// </summary>
        internal static string AntiTamperProtectionDescription {
            get {
                return ResourceManager.GetString("AntiTamperProtectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Anti-tamper helpers injection 的本地化字符串。
        /// </summary>
        internal static string AntiTamperProtectionInjectPhaseName {
            get {
                return ResourceManager.GetString("AntiTamperProtectionInjectPhaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Anti Tamper Protection 的本地化字符串。
        /// </summary>
        internal static string AntiTamperProtectionName {
            get {
                return ResourceManager.GetString("AntiTamperProtectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Encrypting modules... 的本地化字符串。
        /// </summary>
        internal static string Compressor_InjectStub_Encrypting_modules {
            get {
                return ResourceManager.GetString("Compressor_InjectStub_Encrypting_modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No executable module! 的本地化字符串。
        /// </summary>
        internal static string Compressor_Pack_No_executable_module {
            get {
                return ResourceManager.GetString("Compressor_Pack_No_executable_module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This packer reduces the size of output. 的本地化字符串。
        /// </summary>
        internal static string CompressorDescription {
            get {
                return ResourceManager.GetString("CompressorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compressing Packer 的本地化字符串。
        /// </summary>
        internal static string CompressorName {
            get {
                return ResourceManager.GetString("CompressorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This protection encodes and compresses constants in the code. 的本地化字符串。
        /// </summary>
        internal static string ConstantProtectionDescription {
            get {
                return ResourceManager.GetString("ConstantProtectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Constants Protection 的本地化字符串。
        /// </summary>
        internal static string ConstantProtectionName {
            get {
                return ResourceManager.GetString("ConstantProtectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Control flow mangling 的本地化字符串。
        /// </summary>
        internal static string ControlFlowPhaseName {
            get {
                return ResourceManager.GetString("ControlFlowPhaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This protection mangles the code in the methods so that decompilers cannot decompile the methods. 的本地化字符串。
        /// </summary>
        internal static string ControlFlowProtectionDescription {
            get {
                return ResourceManager.GetString("ControlFlowProtectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Control Flow Protection 的本地化字符串。
        /// </summary>
        internal static string ControlFlowProtectionName {
            get {
                return ResourceManager.GetString("ControlFlowProtectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Constants encoding 的本地化字符串。
        /// </summary>
        internal static string EncodePhaseConstantsName {
            get {
                return ResourceManager.GetString("EncodePhaseConstantsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Packer info extraction 的本地化字符串。
        /// </summary>
        internal static string ExtractPhaseName {
            get {
                return ResourceManager.GetString("ExtractPhaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hardening Phase 的本地化字符串。
        /// </summary>
        internal static string HardeningPhaseName {
            get {
                return ResourceManager.GetString("HardeningPhaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This component improves the protection code, making it harder to circumvent it. 的本地化字符串。
        /// </summary>
        internal static string HardeningProtectionDescription {
            get {
                return ResourceManager.GetString("HardeningProtectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Protection Hardening 的本地化字符串。
        /// </summary>
        internal static string HardeningProtectionName {
            get {
                return ResourceManager.GetString("HardeningProtectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Constant encryption helpers injection 的本地化字符串。
        /// </summary>
        internal static string InjectPhaseConstantName {
            get {
                return ResourceManager.GetString("InjectPhaseConstantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resource encryption helpers injection 的本地化字符串。
        /// </summary>
        internal static string InjectPhaseName {
            get {
                return ResourceManager.GetString("InjectPhaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This protection adds invalid metadata to modules to prevent disassembler/decompiler from opening them. 的本地化字符串。
        /// </summary>
        internal static string InvalidMetadataProtectionDescription {
            get {
                return ResourceManager.GetString("InvalidMetadataProtectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid metadata addition 的本地化字符串。
        /// </summary>
        internal static string InvalidMetadataProtectionInvalidMDPhaseName {
            get {
                return ResourceManager.GetString("InvalidMetadataProtectionInvalidMDPhaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Metadata Protection 的本地化字符串。
        /// </summary>
        internal static string InvalidMetadataProtectionName {
            get {
                return ResourceManager.GetString("InvalidMetadataProtectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Encrypting resources... 的本地化字符串。
        /// </summary>
        internal static string MDPhase_EncryptingResourcesText {
            get {
                return ResourceManager.GetString("MDPhase_EncryptingResourcesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Anti-tamper metadata preparation 的本地化字符串。
        /// </summary>
        internal static string MDPhase_Name {
            get {
                return ResourceManager.GetString("MDPhase_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Encoding reference proxies 的本地化字符串。
        /// </summary>
        internal static string ReferenceProxyPhaseName {
            get {
                return ResourceManager.GetString("ReferenceProxyPhaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This protection encodes and hides references to type/method/fields. 的本地化字符串。
        /// </summary>
        internal static string ReferenceProxyProtectionDescription {
            get {
                return ResourceManager.GetString("ReferenceProxyProtectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reference Proxy Protection 的本地化字符串。
        /// </summary>
        internal static string ReferenceProxyProtectionName {
            get {
                return ResourceManager.GetString("ReferenceProxyProtectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This protection encodes and compresses the embedded resources. 的本地化字符串。
        /// </summary>
        internal static string ResourceProtectionDescription {
            get {
                return ResourceManager.GetString("ResourceProtectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resources Protection 的本地化字符串。
        /// </summary>
        internal static string ResourceProtectionName {
            get {
                return ResourceManager.GetString("ResourceProtectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type scrambler 的本地化字符串。
        /// </summary>
        internal static string ScramblePhaseName {
            get {
                return ResourceManager.GetString("ScramblePhaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do some extra works on the protected stub. 的本地化字符串。
        /// </summary>
        internal static string StubProtectionDescription {
            get {
                return ResourceManager.GetString("StubProtectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Module injection 的本地化字符串。
        /// </summary>
        internal static string StubProtectionInjPhaseName {
            get {
                return ResourceManager.GetString("StubProtectionInjPhaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compressor Stub Protection 的本地化字符串。
        /// </summary>
        internal static string StubProtectionName {
            get {
                return ResourceManager.GetString("StubProtectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Packer info encoding 的本地化字符串。
        /// </summary>
        internal static string StubProtectionSigPhaseName {
            get {
                return ResourceManager.GetString("StubProtectionSigPhaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replaces types with generics 的本地化字符串。
        /// </summary>
        internal static string TypeScrambleProtectionDescription {
            get {
                return ResourceManager.GetString("TypeScrambleProtectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type Scrambler 的本地化字符串。
        /// </summary>
        internal static string TypeScrambleProtectionName {
            get {
                return ResourceManager.GetString("TypeScrambleProtectionName", resourceCulture);
            }
        }
    }
}
