//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Confuser.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Confuser.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Module {0} has been delayed the strong name. 的本地化字符串。
        /// </summary>
        internal static string ConfuserEngine_BeginModule_Processing_DelayedStrongName {
            get {
                return ResourceManager.GetString("ConfuserEngine_BeginModule_Processing_DelayedStrongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processing module &apos;{0}&apos;... 的本地化字符串。
        /// </summary>
        internal static string ConfuserEngine_BeginModule_Processing_module {
            get {
                return ResourceManager.GetString("ConfuserEngine_BeginModule_Processing_module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write PE header... 的本地化字符串。
        /// </summary>
        internal static string ConfuserEngine_BeginModule_Processing_PEHeaders {
            get {
                return ResourceManager.GetString("ConfuserEngine_BeginModule_Processing_PEHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processing strong name... 的本地化字符串。
        /// </summary>
        internal static string ConfuserEngine_BeginModule_Processing_StrongName {
            get {
                return ResourceManager.GetString("ConfuserEngine_BeginModule_Processing_StrongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}] SN Key or SN public Key is not provided for a signed module, the output may not be working. 的本地化字符串。
        /// </summary>
        internal static string ConfuserEngine_CheckStrongName1 {
            get {
                return ResourceManager.GetString("ConfuserEngine_CheckStrongName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}] SN Key or SN public Key is provided for an unsigned module, the output may not be working. 的本地化字符串。
        /// </summary>
        internal static string ConfuserEngine_CheckStrongName2 {
            get {
                return ResourceManager.GetString("ConfuserEngine_CheckStrongName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}] Provided SN public Key and signed module&apos;s public key do not match, the output may not be working. 的本地化字符串。
        /// </summary>
        internal static string ConfuserEngine_CheckStrongName3 {
            get {
                return ResourceManager.GetString("ConfuserEngine_CheckStrongName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finalizing... 的本地化字符串。
        /// </summary>
        internal static string ConfuserEngine_Debug_Finalizing {
            get {
                return ResourceManager.GetString("ConfuserEngine_Debug_Finalizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checking Strong Name... 的本地化字符串。
        /// </summary>
        internal static string ConfuserEngine_Inspection_Checking_Strong_Name {
            get {
                return ResourceManager.GetString("ConfuserEngine_Inspection_Checking_Strong_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creating global .cctors... 的本地化字符串。
        /// </summary>
        internal static string ConfuserEngine_Inspection_Creating_global__cctors {
            get {
                return ResourceManager.GetString("ConfuserEngine_Inspection_Creating_global__cctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to resolve dependency assembly &apos;{1}&apos; in module &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ConfuserEngine_Inspection_Failed_to_resolve_dependency {
            get {
                return ResourceManager.GetString("ConfuserEngine_Inspection_Failed_to_resolve_dependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resolving dependencies... 的本地化字符串。
        /// </summary>
        internal static string ConfuserEngine_Inspection_Resolving_dependencies {
            get {
                return ResourceManager.GetString("ConfuserEngine_Inspection_Resolving_dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Packing... 的本地化字符串。
        /// </summary>
        internal static string ConfuserEngine_Pack_Packing {
            get {
                return ResourceManager.GetString("ConfuserEngine_Pack_Packing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cached assemblies: 的本地化字符串。
        /// </summary>
        internal static string ConfuserEngine_PrintEnvironmentInfo_Cached_assemblies {
            get {
                return ResourceManager.GetString("ConfuserEngine_PrintEnvironmentInfo_Cached_assemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Installed Framework Versions: 的本地化字符串。
        /// </summary>
        internal static string ConfuserEngine_PrintEnvironmentInfo_Installed_Framework_Versions {
            get {
                return ResourceManager.GetString("ConfuserEngine_PrintEnvironmentInfo_Installed_Framework_Versions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Protecting packer stub... 的本地化字符串。
        /// </summary>
        internal static string ConfuserEngine_PrintInfo_Protecting_packer_stub {
            get {
                return ResourceManager.GetString("ConfuserEngine_PrintInfo_Protecting_packer_stub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Running on {0}, {1}, {2} bits 的本地化字符串。
        /// </summary>
        internal static string ConfuserEngine_PrintInfo_Running_on {
            get {
                return ResourceManager.GetString("ConfuserEngine_PrintInfo_Running_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Building pipeline... 的本地化字符串。
        /// </summary>
        internal static string ConfuserEngine_RunInternal_Building_pipeline {
            get {
                return ResourceManager.GetString("ConfuserEngine_RunInternal_Building_pipeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Discovered {0} protections, {1} packers. 的本地化字符串。
        /// </summary>
        internal static string ConfuserEngine_RunInternal_Discovered__protections {
            get {
                return ResourceManager.GetString("ConfuserEngine_RunInternal_Discovered__protections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Discovering plugins... 的本地化字符串。
        /// </summary>
        internal static string ConfuserEngine_RunInternal_Discovering_plugins {
            get {
                return ResourceManager.GetString("ConfuserEngine_RunInternal_Discovering_plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error occured during initialization of &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ConfuserEngine_RunInternal_Error_occured_during_initialization {
            get {
                return ResourceManager.GetString("ConfuserEngine_RunInternal_Error_occured_during_initialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initializing... 的本地化字符串。
        /// </summary>
        internal static string ConfuserEngine_RunInternal_Initializing {
            get {
                return ResourceManager.GetString("ConfuserEngine_RunInternal_Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading input modules... 的本地化字符串。
        /// </summary>
        internal static string ConfuserEngine_RunInternal_Loading_input_modules {
            get {
                return ResourceManager.GetString("ConfuserEngine_RunInternal_Loading_input_modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation cancelled. 的本地化字符串。
        /// </summary>
        internal static string ConfuserEngine_RunInternal_Operation_cancelled {
            get {
                return ResourceManager.GetString("ConfuserEngine_RunInternal_Operation_cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resolving component dependency... 的本地化字符串。
        /// </summary>
        internal static string ConfuserEngine_RunInternal_Resolving_component_dependency {
            get {
                return ResourceManager.GetString("ConfuserEngine_RunInternal_Resolving_component_dependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown error occurred. 的本地化字符串。
        /// </summary>
        internal static string ConfuserEngine_RunInternal_Unknown_error_occurred {
            get {
                return ResourceManager.GetString("ConfuserEngine_RunInternal_Unknown_error_occurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Done. 的本地化字符串。
        /// </summary>
        internal static string ConfuserEngine_RunPipeline_Done {
            get {
                return ResourceManager.GetString("ConfuserEngine_RunPipeline_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saving to &apos;{0}&apos;... 的本地化字符串。
        /// </summary>
        internal static string ConfuserEngine_SaveModules_Saving_to {
            get {
                return ResourceManager.GetString("ConfuserEngine_SaveModules_Saving_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Writing module &apos;{0}&apos;... 的本地化字符串。
        /// </summary>
        internal static string ConfuserEngine_WriteModule_Writing_module {
            get {
                return ResourceManager.GetString("ConfuserEngine_WriteModule_Writing_module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading &apos;{0}&apos;... 的本地化字符串。
        /// </summary>
        internal static string Marker_MarkProject_Loading {
            get {
                return ResourceManager.GetString("Marker_MarkProject_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading &apos;{0}&apos;... 的本地化字符串。
        /// </summary>
        internal static string ObfAttrMarker_MarkProject_Loading {
            get {
                return ResourceManager.GetString("ObfAttrMarker_MarkProject_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to instantiate component &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string PluginDiscovery_AddPlugins_Failed_to_instantiate_component {
            get {
                return ResourceManager.GetString("PluginDiscovery_AddPlugins_Failed_to_instantiate_component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to instantiate packer &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string PluginDiscovery_AddPlugins_Failed_to_instantiate_packer {
            get {
                return ResourceManager.GetString("PluginDiscovery_AddPlugins_Failed_to_instantiate_packer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to instantiate protection &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string PluginDiscovery_AddPlugins_Failed_to_instantiate_protection {
            get {
                return ResourceManager.GetString("PluginDiscovery_AddPlugins_Failed_to_instantiate_protection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load built-in protections. 的本地化字符串。
        /// </summary>
        internal static string PluginDiscovery_GetPluginsInternal_Failed_to_load_built_in_protections {
            get {
                return ResourceManager.GetString("PluginDiscovery_GetPluginsInternal_Failed_to_load_built_in_protections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load dynamic cipher library. 的本地化字符串。
        /// </summary>
        internal static string PluginDiscovery_GetPluginsInternal_Failed_to_load_dynamic_cipher_library {
            get {
                return ResourceManager.GetString("PluginDiscovery_GetPluginsInternal_Failed_to_load_dynamic_cipher_library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load plugin &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string PluginDiscovery_GetPluginsInternal_Failed_to_load_plugin {
            get {
                return ResourceManager.GetString("PluginDiscovery_GetPluginsInternal_Failed_to_load_plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load renamer. 的本地化字符串。
        /// </summary>
        internal static string PluginDiscovery_GetPluginsInternal_Failed_to_load_renamer {
            get {
                return ResourceManager.GetString("PluginDiscovery_GetPluginsInternal_Failed_to_load_renamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Executing &apos;{0}&apos; phase... 的本地化字符串。
        /// </summary>
        internal static string ProtectionPipeline_ExecuteStage_Executing {
            get {
                return ResourceManager.GetString("ProtectionPipeline_ExecuteStage_Executing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Watermarking... 的本地化字符串。
        /// </summary>
        internal static string WatermarkingPhase_Execute_Watermarking {
            get {
                return ResourceManager.GetString("WatermarkingPhase_Execute_Watermarking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply watermark 的本地化字符串。
        /// </summary>
        internal static string WatermarkingPhase_Name {
            get {
                return ResourceManager.GetString("WatermarkingPhase_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This applies a watermark to the assembly, showing that ConfuserEx protected the assembly. So people try to reverse the obfuscation know to just give up. 的本地化字符串。
        /// </summary>
        internal static string WatermarkingProtectionDescription {
            get {
                return ResourceManager.GetString("WatermarkingProtectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Watermarking 的本地化字符串。
        /// </summary>
        internal static string WatermarkingProtectionName {
            get {
                return ResourceManager.GetString("WatermarkingProtectionName", resourceCulture);
            }
        }
    }
}
