//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfuserEx.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConfuserEx.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string AboutTabHeaderText {
            get {
                return ResourceManager.GetString("AboutTabHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load plugin &apos; 的本地化字符串。
        /// </summary>
        public static string AppLoadPluginsMsg {
            get {
                return ResourceManager.GetString("AppLoadPluginsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid project! 的本地化字符串。
        /// </summary>
        public static string AppOpenProjErrorMsg {
            get {
                return ResourceManager.GetString("AppOpenProjErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current project has unsaved changes. Do you want to save them? 的本地化字符串。
        /// </summary>
        public static string AppPromptSaveMsg {
            get {
                return ResourceManager.GetString("AppPromptSaveMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading... 的本地化字符串。
        /// </summary>
        public static string ProjectModuleAssemblyNameLoadingText {
            get {
                return ResourceManager.GetString("ProjectModuleAssemblyNameLoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assembly Path: 的本地化字符串。
        /// </summary>
        public static string ProjectModuleAssemblyPathText {
            get {
                return ResourceManager.GetString("ProjectModuleAssemblyPathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Done 的本地化字符串。
        /// </summary>
        public static string ProjectModuleDoneText {
            get {
                return ResourceManager.GetString("ProjectModuleDoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enhanced Strong Name 的本地化字符串。
        /// </summary>
        public static string ProjectModuleEnhancedStrongNameText {
            get {
                return ResourceManager.GetString("ProjectModuleEnhancedStrongNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key Password: 的本地化字符串。
        /// </summary>
        public static string ProjectModuleSNKeyPasswordText {
            get {
                return ResourceManager.GetString("ProjectModuleSNKeyPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key Path: 的本地化字符串。
        /// </summary>
        public static string ProjectModuleSNKeyPathText {
            get {
                return ResourceManager.GetString("ProjectModuleSNKeyPathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Strong Name 的本地化字符串。
        /// </summary>
        public static string ProjectModuleStrongNameText {
            get {
                return ResourceManager.GetString("ProjectModuleStrongNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit module &apos;{0}&apos;... 的本地化字符串。
        /// </summary>
        public static string ProjectModuleTitle {
            get {
                return ResourceManager.GetString("ProjectModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Done 的本地化字符串。
        /// </summary>
        public static string ProjectRuleDoneText {
            get {
                return ResourceManager.GetString("ProjectRuleDoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inherit protections 的本地化字符串。
        /// </summary>
        public static string ProjectRuleInheritProtectionsText {
            get {
                return ResourceManager.GetString("ProjectRuleInheritProtectionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pattern: 的本地化字符串。
        /// </summary>
        public static string ProjectRulePatternText {
            get {
                return ResourceManager.GetString("ProjectRulePatternText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preset :  的本地化字符串。
        /// </summary>
        public static string ProjectRulePresetText {
            get {
                return ResourceManager.GetString("ProjectRulePresetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Protections: 的本地化字符串。
        /// </summary>
        public static string ProjectRuleProtectionsText {
            get {
                return ResourceManager.GetString("ProjectRuleProtectionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit rule... 的本地化字符串。
        /// </summary>
        public static string ProjectRuleTitle {
            get {
                return ResourceManager.GetString("ProjectRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plugins : 的本地化字符串。
        /// </summary>
        public static string ProjectTabAdvancedPluginsText {
            get {
                return ResourceManager.GetString("ProjectTabAdvancedPluginsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Probe Paths : 的本地化字符串。
        /// </summary>
        public static string ProjectTabAdvancedProbePathsText {
            get {
                return ResourceManager.GetString("ProjectTabAdvancedProbePathsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Advanced Settings... 的本地化字符串。
        /// </summary>
        public static string ProjectTabAdvancedTitle {
            get {
                return ResourceManager.GetString("ProjectTabAdvancedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Base Directory :  的本地化字符串。
        /// </summary>
        public static string ProjectTabBaseDirectoryText {
            get {
                return ResourceManager.GetString("ProjectTabBaseDirectoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate Debug Symbols 的本地化字符串。
        /// </summary>
        public static string ProjectTabGenerateDebugSymbolsText {
            get {
                return ResourceManager.GetString("ProjectTabGenerateDebugSymbolsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project 的本地化字符串。
        /// </summary>
        public static string ProjectTabHeaderText {
            get {
                return ResourceManager.GetString("ProjectTabHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drag input modules here 的本地化字符串。
        /// </summary>
        public static string ProjectTabModulesEmptyPromptText {
            get {
                return ResourceManager.GetString("ProjectTabModulesEmptyPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output Directory :  的本地化字符串。
        /// </summary>
        public static string ProjectTabOutputDirectoryText {
            get {
                return ResourceManager.GetString("ProjectTabOutputDirectoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Leave blank for random seed 的本地化字符串。
        /// </summary>
        public static string ProjectTabSeedEmptyPrompt {
            get {
                return ResourceManager.GetString("ProjectTabSeedEmptyPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Seed :  的本地化字符串。
        /// </summary>
        public static string ProjectTabSeedText {
            get {
                return ResourceManager.GetString("ProjectTabSeedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string ProtectTabCancelText {
            get {
                return ResourceManager.GetString("ProtectTabCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Protect! 的本地化字符串。
        /// </summary>
        public static string ProtectTabHeaderText {
            get {
                return ResourceManager.GetString("ProtectTabHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Protect! 的本地化字符串。
        /// </summary>
        public static string ProtectTabProtectText {
            get {
                return ResourceManager.GetString("ProtectTabProtectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 at {0}, {1}:{2:d2} elapsed. 的本地化字符串。
        /// </summary>
        public static string ProtectTabVM_Finish_at_elapsed {
            get {
                return ResourceManager.GetString("ProtectTabVM_Finish_at_elapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed {0} 的本地化字符串。
        /// </summary>
        public static string ProtectTabVM_Finish_Failed {
            get {
                return ResourceManager.GetString("ProtectTabVM_Finish_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finished {0} 的本地化字符串。
        /// </summary>
        public static string ProtectTabVM_Finish_Finished {
            get {
                return ResourceManager.GetString("ProtectTabVM_Finish_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Global settings&gt; 的本地化字符串。
        /// </summary>
        public static string SettingsGlobalSettingsText {
            get {
                return ResourceManager.GetString("SettingsGlobalSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string SettingsTabHeaderText {
            get {
                return ResourceManager.GetString("SettingsTabHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modules :  的本地化字符串。
        /// </summary>
        public static string SettingsTabModulesText {
            get {
                return ResourceManager.GetString("SettingsTabModulesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Packer :  的本地化字符串。
        /// </summary>
        public static string SettingsTabPackerText {
            get {
                return ResourceManager.GetString("SettingsTabPackerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rules :  的本地化字符串。
        /// </summary>
        public static string SettingsTabRulesText {
            get {
                return ResourceManager.GetString("SettingsTabRulesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decode! 的本地化字符串。
        /// </summary>
        public static string StackTraceDecoderDecodeText {
            get {
                return ResourceManager.GetString("StackTraceDecoderDecodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password: 的本地化字符串。
        /// </summary>
        public static string StackTraceDecoderPassword2Text {
            get {
                return ResourceManager.GetString("StackTraceDecoderPassword2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        public static string StackTraceDecoderPasswordText {
            get {
                return ResourceManager.GetString("StackTraceDecoderPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Symbol Map: 的本地化字符串。
        /// </summary>
        public static string StackTraceDecoderSymbolMap2Text {
            get {
                return ResourceManager.GetString("StackTraceDecoderSymbolMap2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Symbol Map 的本地化字符串。
        /// </summary>
        public static string StackTraceDecoderSymbolMapText {
            get {
                return ResourceManager.GetString("StackTraceDecoderSymbolMapText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stack Trace Decoder 的本地化字符串。
        /// </summary>
        public static string StackTraceDecoderTitle {
            get {
                return ResourceManager.GetString("StackTraceDecoderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New project 的本地化字符串。
        /// </summary>
        public static string ToolBarNewProjectText {
            get {
                return ResourceManager.GetString("ToolBarNewProjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open project 的本地化字符串。
        /// </summary>
        public static string ToolBarOpenProjectText {
            get {
                return ResourceManager.GetString("ToolBarOpenProjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save project 的本地化字符串。
        /// </summary>
        public static string ToolBarSaveProjectText {
            get {
                return ResourceManager.GetString("ToolBarSaveProjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stack Trace Decoder 的本地化字符串。
        /// </summary>
        public static string ToolBarStackTraceDecoderText {
            get {
                return ResourceManager.GetString("ToolBarStackTraceDecoderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tools 的本地化字符串。
        /// </summary>
        public static string ToolBarToolsText {
            get {
                return ResourceManager.GetString("ToolBarToolsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Sans 的本地化字符串。
        /// </summary>
        public static string WindowsFontFamily {
            get {
                return ResourceManager.GetString("WindowsFontFamily", resourceCulture);
            }
        }
    }
}
